pool:
  name: Azure Pipelines
  vmImage: windows-latest
  demands: java

trigger:
 branches:
   include:
     - master

steps:
- script: |
   echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
   echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)\bin;$(PATH)"
  displayName: 'Set Java Version'

- task: UseDotNet@2
  displayName: 'Install .NET 6 SDK'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    performMultiLevelLookup: true

- task: Gradle@2
  displayName: 'Build Plugin'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: buildPlugin
    publishJUnitResults: false

- publish: $(System.DefaultWorkingDirectory)/output
  artifact: 'Nuget-Paket'

- task: EvgenyChernyi.telegram-notification-extension.sample-telegram-task.SendTelegramNotification@0
  displayName: 'Send Telegram Notification'
  inputs:
    botToken: '$(token)'
    chats: $(chatId)
    teamUrl: true
    buildNumber: true
    buildQueuedBy: true
  condition: succeededOrFailed()
